services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    env_file:
    - .env
    build: ./backend
    command: >
      sh -c "./wait-for-db.sh db python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - STATIC_URL=/static/
      - DATABASE_URL=postgres://django:django_pass@db:5432/django_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
